Repository newrelic/nri-vsphere, pull requests merged in 2020-07, with the labels that each got.

#38 Feat/performance metrics
  cmd/nri-vsphere/nri-vsphere.go
  config/vsphere-config-win.yml.sample
  config/vsphere-config.yml.sample
  config/vsphere-performance.metrics
  internal/client/client.go
  internal/collect/clusters.go
  internal/collect/collect.go
  internal/collect/datacenters.go
  internal/collect/datastores.go
  internal/collect/hosts.go
  internal/collect/resourcepools.go
  internal/collect/vms.go
  internal/events/eventDispacher.go
  internal/events/events_test.go
  internal/load/datacenter.go
  internal/load/load.go
  internal/performance/performance.go
  internal/performance/performance_test.go
  internal/process/cluster.go
  internal/process/datacenter.go
  internal/process/datastores.go
  internal/process/hosts.go
  internal/process/process.go
  internal/process/resourcepool.go
  internal/process/vms.go
  package.mk
  pkg/windows/nri-386-installer/Product.wxs.template
  pkg/windows/nri-amd64-installer/Product.wxs.template
  vendor/vendor.json
Labels: ready for review

#45 Minor fix in makefile output
  Makefile
Labels: good first issue, ready for review

#40 feat: use infra sdk storage for timestamp cache
  cmd/nri-vsphere/nri-vsphere.go
  internal/cache/cache.go
  internal/cache/cache_test.go
  internal/collect/datacenters.go
  internal/load/load.go
Labels: ready for review

#49 fix(tags): rename tag prefix to label
  internal/process/process.go
Labels: ready for review

#54 fix(license): updating third party notice
  THIRD_PARTY_NOTICES.md
Labels: ready for review

#57 feat(lint): added lint to test process
  Makefile
  cmd/nri-vsphere/nri-vsphere.go
  integration-test/integration_test.go
  internal/collect/clusters.go
  internal/collect/collect_test.go
  internal/collect/datacenters.go
  internal/collect/datastores.go
  internal/collect/hosts.go
  internal/collect/networks.go
  internal/collect/resourcepools.go
  internal/collect/tags.go
  internal/collect/vms.go
  internal/events/events_test.go
  internal/load/datacenter.go
  internal/performance/performance.go
  internal/performance/performance_test.go
Labels: ready for review

#56 fix(Args): cleaned and fixed args
  config/vsphere-config-win.yml.sample
  config/vsphere-config.yml.sample
  internal/collect/datacenters.go
  internal/load/load.go
Labels: ready for review

#50 Fix pipeline
  .gitignore
  Dockerfile.test
  Makefile
  THIRD_PARTY_NOTICES.md
  cmd/nri-vsphere/nri-vsphere.go
  go.mod
  go.sum
  integration-test/integration_test.go
  internal/collect/collect_test.go
  internal/events/eventDispacher.go
  internal/events/events_test.go
  internal/load/load.go
  internal/performance/performance.go
  internal/performance/performance_test.go
  internal/process/datacenter.go
  package.mk
  vendor/vendor.json
Labels: ready for review

#55 fix(perfMetricFile): added default value for argument
  cmd/nri-vsphere/nri-vsphere.go
  internal/load/load.go
  internal/performance/performance.go
Labels: ready for review

#58 fix(makefile) pass the environment variable VERSION to the container
  Makefile
  package.mk
Labels: ready for review

#60 Fix code comments in config files
  config/vsphere-config-win.yml.sample
  config/vsphere-config.yml.sample
  config/vsphere-performance.metrics
Labels: documentation, ready for review

#64 Add code of conduct
  CODE_OF_CONDUCT.md
Labels: ready for review
